name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Dotnet Publish
      run: dotnet publish -o deploy
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: /home/runner/work/QareebApp/QareebApp/deploy/wwwroot
    # changes the base-tag in index.html from '/' to 'QareebApp' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to QareebApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/QareebApp\/" \/>/g' release/wwwroot/index.html